---
run:
  tests: true
linters:
  disable:
    - wsl
    - lll
    - godot
    - nlreturn
    - gomnd
issues:
  exclude-rules:
    - path: cmd/root.go
      text: "missing in Command"
      linters:
        - exhaustivestruct
    - path: cmd/root.go
      text: "VERSION is a global variable"
      linters:
        - gochecknoglobals
    - path: deck/deck.go
      linters:
        - wrapcheck
